// Generated by tools/story/compile_city.py from authored city.json. Do not hand-edit.
#include "Core/CityContent.h"
namespace survival {
World MakeCityCampaign() { World w=MakeCampaign(); w.carryLimitGrams=24000;
w.items["clinic_key"]={60,1};
w.items["medicine_crate"]={900,1};
w.items["water_sample"]={250,1};
w.items["filter"]={3000,1};
w.items["tower_key"]={50,1};
w.items["electronics"]={150,4};
w.items["scrap"]={250,12};
w.items["cloth"]={80,20};
w.items["alcohol"]={180,10};
w.items["medkit"]={280,8};
w.items["letter"]={10,1};
w.items["tools"]={650,1};
w.districts.insert("depot");
w.districts.insert("residential");
w.districts.insert("clinic");
w.districts.insert("pumpworks");
w.districts.insert("relay_tower");
w.districts.insert("market");
w.flags.insert("antenna_ready");
w.flags.insert("break_found");
w.flags.insert("bridge_repaired");
w.flags.insert("briefed");
w.flags.insert("brother_located");
w.flags.insert("brother_rescued");
w.flags.insert("campaign_resolution");
w.flags.insert("clean_water");
w.flags.insert("clinic_open");
w.flags.insert("clinic_stable");
w.flags.insert("contamination_known");
w.flags.insert("ending_leave");
w.flags.insert("ending_stay");
w.flags.insert("evidence_found");
w.flags.insert("filter_found");
w.flags.insert("filter_route");
w.flags.insert("guard_confessed");
w.flags.insert("key_found");
w.flags.insert("letter_delivered");
w.flags.insert("letter_found");
w.flags.insert("lift_ready");
w.flags.insert("logbook_found");
w.flags.insert("medical_plan");
w.flags.insert("medicine_found");
w.flags.insert("orders_found");
w.flags.insert("sample_taken");
w.flags.insert("shelter_ready");
w.flags.insert("testimony_decided");
w.flags.insert("tools_found");
w.flags.insert("tower_key_found");
w.flags.insert("truth_public");
w.flags.insert("truth_sealed");
w.exclusiveGroups.push_back({"truth_public","truth_sealed"});
w.exclusiveGroups.push_back({"ending_stay","ending_leave"});
w.actions.push_back({"meet_dispatch","depot","Связь с диспетчером",{},{},{},{},{"briefed"}});
w.actions.push_back({"inspect_break","depot","Сорванные пломбы",{"briefed"},{},{},{},{"break_found"}});
w.actions.push_back({"read_orders","residential","Чужая подпись",{"break_found"},{},{},{},{"orders_found"}});
w.actions.push_back({"collect_clinic_key","market","Ключ аптечного корпуса",{"generator_running"},{},{},{{"clinic_key",1}},{"key_found"}});
w.actions.push_back({"unlock_clinic","clinic","Открыть лазарет",{"key_found"},{},{{"clinic_key",1}},{},{"clinic_open"}});
w.actions.push_back({"meet_doctor","clinic","Те, кто остался",{"clinic_open"},{},{},{},{"medical_plan"}});
w.actions.push_back({"find_antibiotics","market","Холодильник без питания",{"medical_plan"},{},{},{{"medicine_crate",1}},{"medicine_found"}});
w.actions.push_back({"deliver_antibiotics","clinic","Обычная помощь",{"medical_plan"},{},{{"medicine_crate",1}},{},{"clinic_stable"}});
w.actions.push_back({"check_reservoir","pumpworks","Чёрная вода",{"water_restored"},{},{},{},{"contamination_known"}});
w.actions.push_back({"sample_water","pumpworks","Проба из отстойника",{"contamination_known"},{},{},{{"water_sample",1}},{"sample_taken"}});
w.actions.push_back({"analyze_sample","clinic","Не та причина",{"clinic_stable","sample_taken"},{},{{"water_sample",1}},{},{"evidence_found"}});
w.actions.push_back({"speak_guard","residential","Цена приказа",{"orders_found","evidence_found"},{},{},{},{"guard_confessed"}});
w.actions.push_back({"find_logbook","residential","Журнал ночной смены",{"guard_confessed"},{},{},{},{"logbook_found"}});
w.actions.push_back({"trace_pipeline","pumpworks","Обходная магистраль",{"logbook_found"},{},{},{},{"filter_route"}});
w.actions.push_back({"retrieve_filter","market","Последний кассетный фильтр",{"filter_route"},{},{},{{"filter",1}},{"filter_found"}});
w.actions.push_back({"install_filter","pumpworks","Промывка",{"filter_found","evidence_found"},{},{{"filter",1}},{},{"clean_water"}});
w.actions.push_back({"radio_brother","relay_tower","Знакомый стук",{"clean_water"},{},{},{},{"brother_located"}});
w.actions.push_back({"find_rooftop_key","market","Ключ связиста",{"brother_located"},{},{},{{"tower_key",1}},{"tower_key_found"}});
w.actions.push_back({"rescue_brother","relay_tower","Не оставлять",{"tower_key_found","brother_located"},{},{{"tower_key",1}},{},{"brother_rescued"}});
w.actions.push_back({"assemble_receiver","relay_tower","Голос для всех",{"brother_rescued"},{},{{"electronics",2}},{},{"antenna_ready"}});
w.actions.push_back({"broadcast_truth","relay_tower","Передать журнал открыто",{"antenna_ready","evidence_found"},{"truth_sealed"},{},{},{"truth_public","testimony_decided"}});
w.actions.push_back({"seal_records","relay_tower","Сначала вывести людей",{"antenna_ready","evidence_found"},{"truth_public"},{},{},{"truth_sealed","testimony_decided"}});
w.actions.push_back({"open_shelter","residential","Дом с открытой дверью",{"clean_water","clinic_stable"},{},{},{},{"shelter_ready"}});
w.actions.push_back({"repair_lift","pumpworks","Подъёмник для раненых",{"brother_rescued"},{},{{"scrap",3}},{},{"lift_ready"}});
w.actions.push_back({"settle_districts","depot","Остаться на нулевой отметке",{"shelter_ready","testimony_decided","brother_rescued","local_network"},{"ending_leave"},{},{},{"ending_stay","campaign_resolution"}});
w.actions.push_back({"lead_evacuation","pumpworks","Последний подъём",{"shelter_ready","testimony_decided","brother_rescued","evacuation_beacon","lift_ready"},{"ending_stay"},{},{},{"ending_leave","campaign_resolution"}});
w.actions.push_back({"find_mina_letter","residential","Письмо под дверью",{},{},{},{{"letter",1}},{"letter_found"}});
w.actions.push_back({"deliver_mina_letter","clinic","Доставить письмо",{"letter_found","clinic_open"},{},{{"letter",1}},{{"cloth",2}},{"letter_delivered"}});
w.actions.push_back({"find_tools","market","Ящик слесаря",{},{},{},{{"tools",1}},{"tools_found"}});
w.actions.push_back({"repair_bridge","depot","Чужую работу закончить",{"tools_found"},{},{{"tools",1}},{{"scrap",2}},{"bridge_repaired"}});
w.actions.push_back({"supply_0","depot","Припасы: тайник 1",{},{},{},{{"alcohol",1},{"cloth",2},{"electronics",1},{"scrap",1}},{}});
w.actions.push_back({"supply_1","residential","Припасы: тайник 2",{},{},{},{{"alcohol",1},{"cloth",2},{"electronics",1},{"scrap",1}},{}});
w.actions.push_back({"supply_2","clinic","Припасы: тайник 3",{},{},{},{{"alcohol",1},{"cloth",2},{"scrap",1}},{}});
w.actions.push_back({"supply_3","pumpworks","Припасы: тайник 4",{},{},{},{{"alcohol",1},{"cloth",2},{"scrap",1}},{}});
w.actions.push_back({"supply_4","relay_tower","Припасы: тайник 5",{},{},{},{{"alcohol",1},{"cloth",2},{"scrap",1}},{}});
w.actions.push_back({"supply_5","market","Припасы: тайник 6",{},{},{},{{"alcohol",1},{"cloth",2},{"scrap",1}},{}});
w.actions.push_back({"craft_medkit_0","depot","Собрать перевязочный комплект",{},{},{{"alcohol",1},{"cloth",2}},{{"medkit",1}},{}});
w.actions.push_back({"use_medkit_0","depot","Перевязать раны",{},{},{{"medkit",1}},{},{}});
w.actions.push_back({"craft_medkit_1","clinic","Собрать перевязочный комплект",{},{},{{"alcohol",1},{"cloth",2}},{{"medkit",1}},{}});
w.actions.push_back({"use_medkit_1","clinic","Перевязать раны",{},{},{{"medkit",1}},{},{}});
w.actions.push_back({"craft_medkit_2","residential","Собрать перевязочный комплект",{},{},{{"alcohol",1},{"cloth",2}},{{"medkit",1}},{}});
w.actions.push_back({"use_medkit_2","residential","Перевязать раны",{},{},{{"medkit",1}},{},{}});
w.actions.push_back({"craft_medkit_3","pumpworks","Собрать перевязочный комплект",{},{},{{"alcohol",1},{"cloth",2}},{{"medkit",1}},{}});
w.actions.push_back({"use_medkit_3","pumpworks","Перевязать раны",{},{},{{"medkit",1}},{},{}});
return w; }
const std::vector<StorySite>& CitySites() { static const std::vector<StorySite> sites={
{"search_depot","depot","Катушка стартера","terminal","Арсен",-16.0f,-3.0f,0.0f,false,{}},
{"recover_fuel","depot","Канистра у шлюза","terminal","Арсен",8.0f,7.0f,0.0f,false,{}},
{"repair_generator","depot","Генератор депо","terminal","Лейла",-13.0f,-8.0f,0.0f,false,{"Арсен: Есть ток. Депо снова слышит город.","Лейла: На оба контура мощности не хватит. Реши: лазарет или насосы."}},
{"recover_handle","residential","Ручной привод","terminal","Арсен",-167.0f,-154.0f,0.0f,false,{}},
{"recover_relay","relay_tower","Реле на высоте","terminal","Арсен",177.0f,102.0f,0.0f,false,{}},
{"power_clinic","depot","Ток в лазарет","terminal","Наргис",-10.0f,-8.0f,0.0f,false,{"Наргис: Свет вернулся. Мы можем продолжать.","Лейла: Насосы придётся обходить вручную. Ищи привод в старых дворах."}},
{"power_pumps","depot","Ток на насосы","terminal","Лейла",-7.0f,-8.0f,0.0f,false,{"Лейла: Контур насосной под напряжением.","Наргис: Тогда привезите припасы как можно быстрее. Мы работаем при фонарях."}},
{"open_manual_bypass","pumpworks","Ручной обход","terminal","Арсен",172.0f,-144.0f,0.0f,false,{}},
{"start_pumps","pumpworks","Пуск насосов","terminal","Арсен",180.0f,-144.0f,0.0f,false,{}},
{"connect_local_network","relay_tower","Радиосеть кварталов","terminal","Лейла",180.0f,113.0f,0.0f,false,{"Лейла: Направление передачи выбрано. Осталось вернуть людям чистую воду, собрать раненых и решить судьбу журнала."}},
{"send_evacuation_beacon","relay_tower","Вызов эвакуации","terminal","Лейла",184.0f,113.0f,0.0f,false,{"Лейла: Направление передачи выбрано. Осталось вернуть людям чистую воду, собрать раненых и решить судьбу журнала."}},
{"meet_dispatch","depot","Связь с диспетчером","radio","Лейла",-3.0f,14.0f,0.0f,false,{"Лейла: Арсен? Не подходи к северным воротам. Там больше нет поста.","Арсен: Я пришёл за братом. Ильяс был в смене на насосной.","Лейла: Вчера его отметили в лазарете. Сначала запусти депо: у меня садится последняя батарея.","Арсен: Катушка в мастерской, топливо у шлюза. Помню. Но потом ты расскажешь всё."}},
{"inspect_break","depot","Сорванные пломбы","terminal","Лейла",14.0f,-12.0f,0.0f,false,{"Арсен: Трубу не разорвало. Её перекрыли и сорвали журнал показаний.","Лейла: Распоряжение должно быть в старой конторе. Не обвиняй людей, пока не увидишь подпись."}},
{"read_orders","residential","Чужая подпись","record","Тимур",-180.0f,-151.0f,0.0f,false,{"Арсен: «Изолировать нижние дворы». Подпись начальника охраны. Ни слова об эвакуации.","Тимур: Это моя подпись. Я открыл верхний шлюз, чтобы не затопило лазарет. Нижний уже не открылся.","Арсен: И сколько людей ты оставил там?","Тимур: Пойди в лазарет. Спроси у Наргис, сколько мы тогда вынесли. Потом вернёшься за остальным."}},
{"collect_clinic_key","market","Ключ аптечного корпуса","loot","Лейла",-14.0f,203.0f,0.0f,false,{"Лейла: Ключ должен быть у стойки аптечного фургона. Не трать патроны на каждый звук.","Арсен: Я здесь не ради войны."}},
{"unlock_clinic","clinic","Открыть лазарет","door","Наргис",-178.0f,24.0f,0.0f,false,{"Наргис: Закрой за собой. Они идут на шаги по стеклу.","Арсен: Где Ильяс?","Наргис: Живым ушёл к релейной вышке. Унёс наш передатчик. Чтобы вызвать помощь — так он сказал."}},
{"meet_doctor","clinic","Те, кто остался","person","Наргис",-190.0f,43.0f,0.0f,false,{"Наргис: Здесь нет лекарства от заражения. Но люди умирают и от обычной грязной воды.","Арсен: Если дам ток насосам, ваша палата останется без света.","Наргис: Тогда сделай ручной обход. Выбирай сам. Только не называй людей потерями в отчёте."}},
{"find_antibiotics","market","Холодильник без питания","loot","Арсен",15.0f,217.0f,0.0f,false,{"Арсен: Холодильник ещё холодный. Возьму только запечатанные упаковки.","Наргис: Передай их мне. Дозировки определю я."}},
{"deliver_antibiotics","clinic","Обычная помощь","person","Наргис",-188.0f,46.0f,0.0f,false,{"Наргис: Это не спасёт всех. Но этих двоих — может. Спасибо.","Арсен: Ильяс оставил сообщение?","Наргис: Сказал: «Если брат придёт, не пускайте его в старый отстойник». Значит, тебе туда."}},
{"check_reservoir","pumpworks","Чёрная вода","terminal","Лейла",166.0f,-163.0f,0.0f,false,{"Арсен: Насосы работают, но вода идёт из технического резервуара.","Лейла: Давление вернулось во все районы. Ты можешь остановить поток.","Арсен: Сначала узнаю, что в нём. Иначе мы оставим их и без воды, и без ответа."}},
{"sample_water","pumpworks","Проба из отстойника","loot","Арсен",155.0f,-169.0f,0.0f,false,{"Арсен: На стенке свежие следы. Ильяс был здесь после закрытия шлюзов."}},
{"analyze_sample","clinic","Не та причина","terminal","Наргис",-171.0f,45.0f,0.0f,false,{"Наргис: В пробе промышленная взвесь. Это опасно, но не объясняет заражённых.","Арсен: Значит, изоляцию объявили из-за другой причины?","Наргис: Или прикрыли ею аварию. Найди фильтры. Город сейчас нуждается не в красивом объяснении."}},
{"speak_guard","residential","Цена приказа","person","Тимур",-186.0f,-164.0f,0.0f,false,{"Тимур: Мне приказали удержать людей до прибытия колонны. Колонна не приехала.","Арсен: Ты мог открыть ворота.","Тимур: Да. Вот чего я боялся сказать. Журнал в подвале; коды резервного склада внутри.","Арсен: Пойдёшь со мной. Не как охранник. Носилки понесёшь."}},
{"find_logbook","residential","Журнал ночной смены","record","Арсен",-174.0f,-176.0f,0.0f,false,{"Арсен: Три имени перечёркнуты. Напротив Ильяса — стрелка к радиостанции.","Лейла: Сохрани страницы. Люди должны узнать не только то, что удобно победителям."}},
{"trace_pipeline","pumpworks","Обходная магистраль","terminal","Лейла",196.0f,-177.0f,0.0f,false,{"Арсен: Технический резервуар подключён в обход фильтров. Я могу вернуть старую схему.","Лейла: Фильтры вывезли в рыночный склад после затопления."}},
{"retrieve_filter","market","Последний кассетный фильтр","loot","Арсен",20.0f,197.0f,0.0f,false,{"Арсен: Кассета цела. Тяжёлая, но довезу.","Наргис: Не обещай людям чистую воду, пока не запустишь контрольный цикл."}},
{"install_filter","pumpworks","Промывка","terminal","Арсен",190.0f,-143.0f,0.0f,false,{"Арсен: Первый поток — в дренаж. Второй — на пробу. Только третий в сеть.","Лейла: Наргис подтверждает: вода годится для технической обработки. Для питья пока нужна дополнительная очистка.","Арсен: Это начало. Не чудо."}},
{"radio_brother","relay_tower","Знакомый стук","radio","Ильяс",169.0f,92.0f,0.0f,false,{"Ильяс: Арсен? Я думал, ты уехал.","Арсен: Я тоже. Где ты?","Ильяс: Внизу вышки. Лестницу завалило. Не включай прожекторы: они собираются на площадке.","Арсен: Найду служебный ключ. Сиди тихо."}},
{"find_rooftop_key","market","Ключ связиста","loot","Лейла",-19.0f,224.0f,0.0f,false,{"Лейла: Дежурный связист ночевал у южного киоска. Ключи обычно под приёмником."}},
{"rescue_brother","relay_tower","Не оставлять","person","Ильяс",192.0f,101.0f,0.0f,false,{"Ильяс: Я видел автобусы. Они были пустыми, Арсен. Их не собирались отправлять вниз.","Арсен: Ты пытался передать журнал?","Ильяс: Я пытался дозвониться тебе.","Арсен: Я здесь. Остальное скажешь, когда выйдем."}},
{"assemble_receiver","relay_tower","Голос для всех","craft","Лейла",176.0f,117.0f,0.0f,false,{"Лейла: Две платы, одно рабочее реле и антенна. Этого хватит на город или на дальний маяк.","Арсен: А хватит, чтобы передать журнал?","Лейла: Хватит. И после передачи никто не сможет сделать вид, что не слышал."}},
{"broadcast_truth","relay_tower","Передать журнал открыто","choice","Арсен",178.0f,120.0f,0.0f,false,{"Арсен: Всем, кто слышит: называю имена тех, кто остался в нижних дворах. И имена тех, кто подписал приказ.","Тимур: Моё называй первым.","Лейла: Запись пошла. Теперь это не только наша история."}},
{"seal_records","relay_tower","Сначала вывести людей","choice","Арсен",182.0f,120.0f,0.0f,false,{"Арсен: Передадим маршруты и список раненых. Журнал остаётся у Наргис.","Наргис: Я сохраню его. Но обещаю не молчать вечно.","Лейла: Тогда начинаем с живых."}},
{"open_shelter","residential","Дом с открытой дверью","terminal","Наргис",-190.0f,-148.0f,0.0f,false,{"Наргис: В этом доме можно отделить больных от остальных. Нужны тёплая вода и дежурные.","Тимур: Я останусь у двери. Без замка снаружи."}},
{"repair_lift","pumpworks","Подъёмник для раненых","craft","Арсен",202.0f,-146.0f,0.0f,false,{"Ильяс: На руках по лестнице мы всех не поднимем.","Арсен: Привод восстановлен. Теперь помоги закрепить носилки."}},
{"settle_districts","depot","Остаться на нулевой отметке","finale","Лейла",-3.0f,10.0f,0.0f,false,{"Лейла: Районы слышат друг друга. Первые дежурные уже у насосной.","Ильяс: И что теперь?","Арсен: Теперь каждый день придётся делать то, что сегодня получилось один раз.","Наргис: Город ещё болен. Но больше не молчит.","Исследование продолжается. Незавершённые просьбы жителей и найденные припасы остаются в мире."}},
{"lead_evacuation","pumpworks","Последний подъём","finale","Лейла",210.0f,-130.0f,0.0f,false,{"Лейла: Маяк принят. Колонна будет у верхней дороги на рассвете.","Тимур: Сперва раненые. Я пойду последним.","Ильяс: Ты ведь вернёшься?","Арсен: Здесь осталась работа. И люди, которые не захотят уезжать.","Маршрут эвакуации открыт. До ухода можно свободно исследовать районы и закончить просьбы жителей."}},
{"find_mina_letter","residential","Письмо под дверью","record","Записка",-198.0f,-179.0f,0.0f,true,{"Записка: «Мама, я у доктора. Не ищи меня в школе. Мина»."}},
{"deliver_mina_letter","clinic","Доставить письмо","person","Наргис",-199.0f,37.0f,0.0f,true,{"Наргис: Её мать здесь. Я отдам письмо сама.","Арсен: Пусть знает, что девочка выбралась."}},
{"find_tools","market","Ящик слесаря","loot","Записка",7.0f,232.0f,0.0f,true,{"Записка: «Кто возьмёт — закончите перила на мосту. Борис»."}},
{"repair_bridge","depot","Чужую работу закончить","craft","Арсен",4.0f,4.0f,0.0f,true,{"Арсен: Крепления держат. Можно вести людей через мост.","Лейла: Имя слесаря оставь на ящике. Пусть знают, кому сказать спасибо."}},
{"supply_0","depot","Припасы: тайник 1","loot","Арсен",18.0f,15.0f,0.0f,true,{"Арсен: Возьму необходимое. Кто-то приготовил эти припасы не зря."}},
{"supply_1","residential","Припасы: тайник 2","loot","Арсен",-161.0f,-181.0f,0.0f,true,{"Арсен: Возьму необходимое. Кто-то приготовил эти припасы не зря."}},
{"supply_2","clinic","Припасы: тайник 3","loot","Арсен",-204.0f,57.0f,0.0f,true,{"Арсен: Возьму необходимое. Кто-то приготовил эти припасы не зря."}},
{"supply_3","pumpworks","Припасы: тайник 4","loot","Арсен",162.0f,-132.0f,0.0f,true,{"Арсен: Возьму необходимое. Кто-то приготовил эти припасы не зря."}},
{"supply_4","relay_tower","Припасы: тайник 5","loot","Арсен",199.0f,83.0f,0.0f,true,{"Арсен: Возьму необходимое. Кто-то приготовил эти припасы не зря."}},
{"supply_5","market","Припасы: тайник 6","loot","Арсен",-27.0f,201.0f,0.0f,true,{"Арсен: Возьму необходимое. Кто-то приготовил эти припасы не зря."}},
{"craft_medkit_0","depot","Собрать перевязочный комплект","craft","Арсен",-18.0f,5.0f,0.0f,true,{"Арсен: Чистая ткань и антисептик. Пригодится до следующего лазарета."}},
{"use_medkit_0","depot","Перевязать раны","heal","Арсен",-16.0f,5.0f,0.0f,true,{"Арсен: Можно идти дальше."}},
{"craft_medkit_1","clinic","Собрать перевязочный комплект","craft","Арсен",-195.0f,51.0f,0.0f,true,{"Арсен: Чистая ткань и антисептик. Пригодится до следующего лазарета."}},
{"use_medkit_1","clinic","Перевязать раны","heal","Арсен",-193.0f,51.0f,0.0f,true,{"Арсен: Можно идти дальше."}},
{"craft_medkit_2","residential","Собрать перевязочный комплект","craft","Арсен",-177.0f,-146.0f,0.0f,true,{"Арсен: Чистая ткань и антисептик. Пригодится до следующего лазарета."}},
{"use_medkit_2","residential","Перевязать раны","heal","Арсен",-175.0f,-146.0f,0.0f,true,{"Арсен: Можно идти дальше."}},
{"craft_medkit_3","pumpworks","Собрать перевязочный комплект","craft","Арсен",188.0f,-155.0f,0.0f,true,{"Арсен: Чистая ткань и антисептик. Пригодится до следующего лазарета."}},
{"use_medkit_3","pumpworks","Перевязать раны","heal","Арсен",190.0f,-155.0f,0.0f,true,{"Арсен: Можно идти дальше."}},
}; return sites; }
const StorySite* FindCitySite(const std::string& id) { for(const auto& site:CitySites()) if(site.id==id) return &site; return nullptr; }
}
