#!/usr/bin/env python3
"""Compile authored campaign data into the actual native game; no runtime JSON dependency."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[2];d=json.loads((root/'BuildData/story/city.json').read_text())
def quote(x):return json.dumps(x,ensure_ascii=False)
def flags(x):return '{'+','.join(map(quote,x))+'}'
def counts(x):return '{'+','.join('{'+quote(k)+','+str(v)+'}' for k,v in sorted(x.items()))+'}'
ids=[s['id'] for s in d['sites']];assert len(ids)==len(set(ids))
assert all(len(s['position'])==3 and max(map(abs,s['position']))<400 for s in d['sites'])
known={x['id'] for x in d['districts']};assert all(s['district'] in known for s in d['sites'])
s=['// Generated by tools/story/compile_city.py from authored city.json. Do not hand-edit.','#include "Core/CityContent.h"','namespace survival {','World MakeCityCampaign() { World w=MakeCampaign(); w.carryLimitGrams=24000;']
for k,(g,limit) in d['items'].items():s.append('w.items['+quote(k)+']={'+str(g)+','+str(limit)+'};')
for x in d['districts']:s.append('w.districts.insert('+quote(x['id'])+');')
for f in sorted({f for a in d['actions'] for f in a['sets']}):s.append('w.flags.insert('+quote(f)+');')
for g in d['exclusive_groups']:s.append('w.exclusiveGroups.push_back('+flags(g)+');')
for a in d['actions']:s.append('w.actions.push_back({'+','.join([quote(a['id']),quote(a['district']),quote(a['title']),flags(a['required']),flags(a['forbids']),counts(a['consumes']),counts(a['grants']),flags(a['sets'])])+'});')
s+=['return w; }','const std::vector<StorySite>& CitySites() { static const std::vector<StorySite> sites={']
for p in d['sites']:s.append('{'+','.join([quote(p['id']),quote(p['district']),quote(p['title']),quote(p['kind']),quote(p['speaker'])]+[f'{float(v)}f' for v in p['position']]+['true' if p.get('optional') else 'false',flags(p['lines'])])+'},')
s+=['}; return sites; }','const StorySite* FindCitySite(const std::string& id) { for(const auto& site:CitySites()) if(site.id==id) return &site; return nullptr; }','}']
(root/'Source/PocoSurvival/Private/Core/CityContent.cpp').write_text('\n'.join(s)+'\n')
print('CITY_NATIVE_CONTENT',len(d['sites']),'sites',len(d['actions'])+11,'actions')
